### ISSUE TITLE
name change for azure build yaml value

### ISSUE THREAD

**Issue by tom-myers1** [benday/build-utilities#4]
hey, did the name of the extension intentionally change with the last release (yesterday)? and is it going to stay with the new name bendayconsulting.build-task.setjsonvalue.setjsonvalue@1 instead of the old name bendayconsulting.build-task.setjsonvalue.setjsonconfigconnectionstring@1? just checking if i should update all my builds? appreciate the utility - thanks for creating it!

**Comment by benday** [comment]
Hi Tom --

Yes, the name changed in order to fix a bug that a customer was having.  There was a misconfiguration in the "setjsonvalue" task where the internal name was actually the same value as the "set json connection string" task.  It was causing a problem where TFS2015-based builds would run the wrong task.  

Glad you like the utility!

-Ben
